include:
  - local: 'ci-templates/templates.yml'

stages:
  - test_box
  - test_merge
  - test_clean_and_merge
  - test_spatial_interp
  - test_time_interp
  - build
  - test_arti

test_box_python:
  stage: test_box
  # when: manual
  image:
    name: artifactory.thalesdigital.io/private-docker-aes-datavalo/floria/tests_non_regression/docker_images/alexgleith-cdo:latest
    entrypoint: [""]
  script:
    - echo "Environment setup"
    - sh ci-scripts/get_env_test_box.sh
    - echo "Test launching"
    - python3 FORECAST/BOX/Docker/app/box.py --logs_file "./tests_non_regression/logs/BOX.log" --metaparams "./tests_non_regression/config/metaparams.json" --output_dir "./tests_non_regression/outputs/output_BOX/" --input_dir "./tests_non_regression/data/input_BOX/" --input_file "merge_spatial_interp_forecast.nc" --output_file "merge_box_forecast.nc"
  tags:
    - autoscale
  artifacts:
    paths:
      - ./tests_non_regression/references/output_BOX/merge_box_forecast.nc
      - ./tests_non_regression/outputs/output_BOX/merge_box_forecast.nc 


compare_ref_and_res_box:
  stage: test_box
  # when: manual
  extends: .compare_template
  # when: manual
  variables:
    REF_PATH: "./tests_non_regression/references/output_BOX/merge_box_forecast.nc"
    RES_PATH: "./tests_non_regression/outputs/output_BOX/merge_box_forecast.nc"
  needs: ['test_box_python']

test_merge_python:
  stage: test_merge
  # when: manual
  image:
    name: artifactory.thalesdigital.io/private-docker-aes-datavalo/floria/tests_non_regression/docker_images/python-3.8.10-slim:latest
    entrypoint: [""]
  script:
    - echo "Environment setup"
    - sh ci-scripts/get_env_test_merge.sh
    - echo "Pythons setup"
    - cd FORECAST/MERGE/Docker
    - pip install -r requirements.txt
    - cd ../../../
    - apt-get install libeccodes-dev -y
    - echo "Test launching"
    - python3 FORECAST/MERGE/Docker/app/extract.py --logs_file "./tests_non_regression/logs/MERGE.log" --config_file "./share/config.json" --params_time "./tests_non_regression/config/params_time.json" --params_variables "./tests_non_regression/config/params_variables.json" --metaparams "./tests_non_regression/config/metaparams.json" --output_dir "./tests_non_regression/outputs/output_MERGE" --input_dir "./tests_non_regression/data/input_MERGE" --output_file merge_forecast.nc
  tags:
    - autoscale
  artifacts:
    paths:
      - ./tests_non_regression/references/output_MERGE/ICON_EU_merge_forecast.nc
      - ./tests_non_regression/references/output_MERGE/ICON_GLOBAL_merge_forecast.nc
      - ./tests_non_regression/references/output_MERGE/IFS_merge_forecast.nc
      - ./tests_non_regression/outputs/output_MERGE/ICON_EU_merge_forecast.nc
      - ./tests_non_regression/outputs/output_MERGE/ICON_GLOBAL_merge_forecast.nc
      - ./tests_non_regression/outputs/output_MERGE/IFS_merge_forecast.nc

compare_ref_and_res_merge:
  stage: test_merge
  extends: .compare_template
  variables:
    REF_PATH: "./tests_non_regression/references/output_MERGE/"
    RES_PATH: "./tests_non_regression/outputs/output_MERGE/"
  needs: ['test_merge_python']

test_clean_and_merge_python:
  stage: test_clean_and_merge
  # when: manual
  image:
    name: artifactory.thalesdigital.io/private-docker-aes-datavalo/floria/tests_non_regression/docker_images/python-3.8.10-slim:latest
    entrypoint: [""]
  script:
    - echo "Environment setup"
    - sh ci-scripts/get_env_test_clean_and_merge.sh
    - echo "Pythons setup"
    - cd FORECAST/CLEAN_AND_MERGE/Docker
    - pip install -r requirements.txt
    - cd ../../../
    - apt-get install libeccodes-dev -y
    - echo "Test launching"
    - python3 FORECAST/CLEAN_AND_MERGE/Docker/app/clean.py --logs_file "./tests_non_regression/logs/CLEAN_AND_MERGE.log" --params_time "./tests_non_regression/config/params_time.json" --params_variables "./tests_non_regression/config/params_variables.json" --metaparams "./tests_non_regression/config/metaparams.json" --output_dir "./tests_non_regression/outputs/output_CLEAN_AND_MERGE/" --input_dir "./tests_non_regression/data/input_CLEAN_AND_MERGE/" --output_file "merge_time_interp_forecast.nc"
  tags:
    - autoscale
  artifacts:
    paths:
      - ./tests_non_regression/references/output_CLEAN_AND_MERGE/merge_time_interp_forecast.nc
      - ./tests_non_regression/outputs/output_CLEAN_AND_MERGE/merge_time_interp_forecast.nc

compare_ref_and_res_clean_and_merge:
  stage: test_clean_and_merge
  # when: manual
  extends: .compare_template
  variables:
    REF_PATH: "./tests_non_regression/references/output_CLEAN_AND_MERGE/merge_time_interp_forecast.nc"
    RES_PATH: "./tests_non_regression/outputs/output_CLEAN_AND_MERGE/merge_time_interp_forecast.nc"
  needs: ['test_clean_and_merge_python']

test_spatial_interp_python:
  stage: test_spatial_interp
  # when: manual
  image:
    name: artifactory.thalesdigital.io/private-docker-aes-datavalo/floria/tests_non_regression/docker_images/alexgleith-cdo:latest
    entrypoint: [""]
  script:
    - echo "Environment setup"
    - sh ci-scripts/get_env_test_spatial_interp.sh
    - echo "Test launching"
    - python3 FORECAST/SPATIAL_INTERP/Docker/app/remap.py --logs_file "./tests_non_regression/logs/SPATIAL_INTERP.log" --metaparams "./tests_non_regression/config/metaparams.json" --output_dir "./tests_non_regression/outputs/output_SPATIAL_INTERP/" --input_dir "./tests_non_regression/data/input_SPATIAL_INTERP/" --input_file "merge_time_interp_forecast.nc" --output_file "merge_spatial_interp_forecast.nc"
    - ls -lR ./tests_non_regression
  tags:
    - autoscale
  artifacts:
    paths:
      - ./tests_non_regression/references/output_SPATIAL_INTERP/merge_spatial_interp_forecast.nc
      - ./tests_non_regression/outputs/output_SPATIAL_INTERP/merge_spatial_interp_forecast.nc

compare_ref_and_res_spatial_interp:
  stage: test_spatial_interp
  extends: .compare_template
  variables:
    REF_PATH: "./tests_non_regression/references/output_SPATIAL_INTERP/merge_spatial_interp_forecast.nc"
    RES_PATH: "./tests_non_regression/references/output_SPATIAL_INTERP/merge_spatial_interp_forecast.nc"
  needs: ['test_spatial_interp_python']


test_time_interp_python:
  stage: test_time_interp
  # when: manual
  image:
    name: artifactory.thalesdigital.io/private-docker-aes-datavalo/floria/tests_non_regression/docker_images/alexgleith-cdo:latest
    entrypoint: [""]
  script:
    - echo "Environment setup"
    - sh ci-scripts/get_env_test_time_interp.sh
    - echo "Test launching"
    - python3 FORECAST/TIME_INTERP/Docker/app/interp.py --logs_file "./tests_non_regression/logs/TIME_INTERP.log" --params_time "./tests_non_regression/config/params_time.json" --output_dir "./tests_non_regression/outputs/output_TIME_INTERP" --input_dir "./tests_non_regression/data/input_TIME_INTERP/"
    - ls -lR ./tests_non_regression
  tags:
    - autoscale
  artifacts:
    paths:
      - ./tests_non_regression/references/output_TIME_INTERP/ICON_EU_merge_forecast_interp.nc
      - ./tests_non_regression/references/output_TIME_INTERP/ICON_GLOBAL_merge_forecast_interp.nc
      - ./tests_non_regression/references/output_TIME_INTERP/IFS_merge_forecast_interp.nc
      - ./tests_non_regression/outputs/output_TIME_INTERP/ICON_EU_merge_forecast_interp.nc
      - ./tests_non_regression/outputs/output_TIME_INTERP/ICON_GLOBAL_merge_forecast_interp.nc
      - ./tests_non_regression/outputs/output_TIME_INTERP/IFS_merge_forecast_interp.nc

compare_ref_and_res_time_interp:
  stage: test_time_interp
  extends: .compare_template
  variables:
    REF_PATH: "./tests_non_regression/references/output_TIME_INTERP/"
    RES_PATH: "./tests_non_regression/outputs/output_TIME_INTERP/"
  needs: ['test_time_interp_python']

build_kaniko:
  stage: build
  # when: manual
  image:
    name: artifactory.thalesdigital.io/private-docker-aes-datavalo/floria/tests_non_regression/docker_images/gcr.io-kaniko-project-executor:latest
    entrypoint: [""]
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR/FORECAST/BOX/Docker --dockerfile $CI_PROJECT_DIR/FORECAST/BOX/Docker/Dockerfile --no-push
    # Workdir cleaning between each kaniko execution
    - rm -rf /home/app/*
    - rm -rf /data/*
    - /kaniko/executor --context $CI_PROJECT_DIR/FORECAST/CLEAN_AND_MERGE/Docker --dockerfile $CI_PROJECT_DIR/FORECAST/CLEAN_AND_MERGE/Docker/Dockerfile --no-push
    # Workdir cleaning between each kaniko execution
    - rm -rf /home/app/*
    - rm -rf /data/*
    - /kaniko/executor --context $CI_PROJECT_DIR/FORECAST/MERGE/Docker --dockerfile $CI_PROJECT_DIR/FORECAST/MERGE/Docker/Dockerfile --no-push
    # Workdir cleaning between each kaniko execution
    - rm -rf /home/app/*
    - rm -rf /data/*
    - /kaniko/executor --context $CI_PROJECT_DIR/FORECAST/REMAP/Docker --dockerfile $CI_PROJECT_DIR/FORECAST/REMAP/Docker/Dockerfile --no-push
    # Workdir cleaning between each kaniko execution
    - rm -rf /home/app/*
    - rm -rf /data/*
    - /kaniko/executor --context $CI_PROJECT_DIR/FORECAST/SPATIAL_INTERP/Docker --dockerfile $CI_PROJECT_DIR/FORECAST/SPATIAL_INTERP/Docker/Dockerfile --no-push
    # Workdir cleaning between each kaniko execution
    - rm -rf /home/app/*
    - rm -rf /data/*
    - /kaniko/executor --context $CI_PROJECT_DIR/FORECAST/TIME_INTERP/Docker --dockerfile $CI_PROJECT_DIR/FORECAST/TIME_INTERP/Docker/Dockerfile --no-push
    # Workdir cleaning between each kaniko execution
    - rm -rf /home/app/*
    - rm -rf /data/*
    - /kaniko/executor --context $CI_PROJECT_DIR/FORECAST/REQUEST/GFS/Docker --dockerfile $CI_PROJECT_DIR/FORECAST/REQUEST/GFS/Docker/Dockerfile --no-push
    # Workdir cleaning between each kaniko execution
    - rm -rf /home/app/*
    - rm -rf /data/*
    - /kaniko/executor --context $CI_PROJECT_DIR/FORECAST/REQUEST/ICON_EU/Docker --dockerfile $CI_PROJECT_DIR/FORECAST/REQUEST/ICON_EU/Docker/Dockerfile --no-push
    # Workdir cleaning between each kaniko execution
    - rm -rf /home/app/*
    - rm -rf /data/*
    - /kaniko/executor --context $CI_PROJECT_DIR/FORECAST/REQUEST/ICON_GLOBAL/Docker --dockerfile $CI_PROJECT_DIR/FORECAST/REQUEST/ICON_GLOBAL/Docker/Dockerfile --no-push
    # Workdir cleaning between each kaniko execution
    - rm -rf /home/app/*
    - rm -rf /data/*
    - /kaniko/executor --context $CI_PROJECT_DIR/FORECAST/REQUEST/IFS/Docker --dockerfile $CI_PROJECT_DIR/FORECAST/REQUEST/IFS/Docker/Dockerfile --no-push

  tags:
    - autoscale